// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWWs2BFnQrk9MiqAHfg2YDdWCxyfvFzE',
    appId: '1:169093138801:web:6048d91a557ad1c44a8ed0',
    messagingSenderId: '169093138801',
    projectId: 'firestorecloud-384b4',
    authDomain: 'firestorecloud-384b4.firebaseapp.com',
    storageBucket: 'firestorecloud-384b4.firebasestorage.app',
    measurementId: 'G-Y7V2L1RXJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvgrfrI9XwuP3-e7MLeL3tQZeFeXDw4c',
    appId: '1:169093138801:android:d6d849cd2a1d53204a8ed0',
    messagingSenderId: '169093138801',
    projectId: 'firestorecloud-384b4',
    storageBucket: 'firestorecloud-384b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9JB3HmgN932SKGbX02NYzBjMOBc7_Qc',
    appId: '1:169093138801:ios:8f6302416426d3974a8ed0',
    messagingSenderId: '169093138801',
    projectId: 'firestorecloud-384b4',
    storageBucket: 'firestorecloud-384b4.firebasestorage.app',
    iosBundleId: 'com.example.codeStructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi9JB3HmgN932SKGbX02NYzBjMOBc7_Qc',
    appId: '1:169093138801:ios:8f6302416426d3974a8ed0',
    messagingSenderId: '169093138801',
    projectId: 'firestorecloud-384b4',
    storageBucket: 'firestorecloud-384b4.firebasestorage.app',
    iosBundleId: 'com.example.codeStructure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATWWs2BFnQrk9MiqAHfg2YDdWCxyfvFzE',
    appId: '1:169093138801:web:ff2e6f7613c1f13d4a8ed0',
    messagingSenderId: '169093138801',
    projectId: 'firestorecloud-384b4',
    authDomain: 'firestorecloud-384b4.firebaseapp.com',
    storageBucket: 'firestorecloud-384b4.firebasestorage.app',
    measurementId: 'G-2NY88YVDFE',
  );
}
